.TH man 1 "20 Mar 2022" "1.0" "cd man page"
.SH NAME
cd \- change the working directory 
.SH SYNOPSIS
cd [-L|[-P [-e]] [-@]] [dir]
.SH DESCRIPTION
The cd command is used to change the current working directory.

1. If no \fBdirecotry\fP operand is given, then the current working directory will be changed to the users home directory.
.SH OPTIONS
\fB-L\fP
    Handle the operand dot-dot logically; symbolic link components shall not be resolved before dot-dot components are processed.

\fB-P\fP
    Handle the operand dot-dot physically; symbolic link components shall be resolved before dot-dot components are processed.

\fB-e\fP
    If the -P option is supplied, and the current working directory cannot be determined successfully, exit with a non-zero status

\fB-@\fP
    On systems that support it, present a file with extended attributes as a directory containing the file attributes

.SH BUGS
No known bugs.
.SH AUTHOR
Ramin Radmand (rradm367@mtroyal.ca)