#!/bin/bash

NFLAG='false'
LENGTH=8
LFLAG='false'
UFLAG='false'
DFLAG='false';
SFLAG='false';
EFLAG='false';

UPPER="A-Z"
LOWER="a-z"
DIGITS="0-9"
SYMBOL="@#$%&*"

while [ $# -gt 0 ]; do
    case $1 in
    -*n) if [ $# -gt 1 ]; then
             NFLAG='true'
             LENGTH=$2
             shift
         fi
         ;;
    -*l*)
        LFLAG='true'
        ;;&
    -*u*)
        UFLAG='true'
        ;;&
    -*d*)
        DFLAG='true'
        ;;&
    -*s*)
        SFLAG='true'
        ;;&
    -*e*)
        EFLAG='true'
        ;;
    *) ;;
    esac
    shift
done

if [ $LENGTH -le 0 ]; then
    echo "passgen: invalid -n argument '$LENGTH'"
else

    if [ $LFLAG = 'false' -a $UFLAG = 'false' -a $DFLAG = 'false' -a $SFLAG = 'false' ]; then
        LFLAG=true
    fi
    
    if [ $EFLAG = 'true' ]; then
        LOWER="a-km-z"
        UPPER="A-HJ-NP-Z"
        DIGITS="2-9"
    fi
    
    CHARS=''
    if [ $LFLAG = 'true' ]; then
        CHARS="$LOWER$CHARS"
    fi
    if [ $UFLAG = 'true' ]; then
        CHARS="$UPPER$CHARS"
    fi
    if [ $DFLAG = 'true' ]; then
        CHARS="$DIGITS$CHARS"
    fi
    if [ $SFLAG = 'true' ]; then
        CHARS="$SYMBOL$CHARS"
    fi

    echo `tr -dc $CHARS < /dev/urandom | head -c${1:-$LENGTH};echo;`
fi
