#!/bin/bash

NFLAG='false'
LENGTH=8
LFLAG='false'
UFLAG='false'
DFLAG='false'
SFLAG='false'
EFLAG='false'
PFLAG='false'
USERID=''
USER_EXISTS=0
FLAGSET=''

UPPER="A-Z"
LOWER="a-z"
DIGITS="0-9"
SYMBOL="@#$%&*"

while [ $# -gt 0 ]; do
    FLAGSET='false'
    if [[ $1 =~ ^-([^ludsenp]) ]] || [[  $1 =~ ^-[ludse]+([^ludsenp]) ]]; then
		BADFLAG=${BASH_REMATCH[1]}
		echo "passgen: - invalid option -- '$BADFLAG'" 1>&2
		exit 1
    fi
    if [[ $1 =~ ^-[^n]*p$ ]]; then
		if [ $# -lt 2 ] || [[ $2 =~ ^- ]]; then
			echo "passgen: option requires an argument -- 'p'" 1>&2
			exit 1
		else
			PFLAG=true
			FLAGSET=true     	
			USERID=$2
			shift
		fi
    elif [[ $1 =~ ^-[^n]*p(.*) ]]; then
		PFLAG=true
		FLAGSET=true
		USERID=${BASH_REMATCH[1]}
    elif [[ $1 =~ ^-[^p]*n+$ ]]; then
		if [ $# -lt 2 ] || [[ $2 =~ ^-[^0-9] ]]; then
			echo "passgen: option requires an argument -- 'n'" 1>&2
			exit 1
		else
			NFLAG=true
			FLAGSET=true
			LENGTH=$2
			shift
		fi
    elif [[ $1 =~ -[^p]*n+(.*) ]] ;then
		NFLAG=true
		FLAGSET=true
		LENGTH=${BASH_REMATCH[1]}
    fi

    if [[ $1 =~ ^-[^np]*l ]]; then
		LFLAG=true
		FLAGSET=true
    fi
    if [[ $1 =~ ^-[^np]*u ]]; then
		UFLAG=true
		FLAGSET=true
    fi
    if [[ $1 =~ ^-[^np]*d ]]; then
		DFLAG=true
		FLAGSET=true
    fi
    if [[ $1 =~ ^-[^np]*s ]]; then
		SFLAG=true
		FLAGSET=true
    fi
    if [[ $1 =~ ^-[^np]*e ]]; then
		EFLAG=true
		FLAGSET=true
    fi

    if [ $FLAGSET = 'false' ]; then
		echo "passgen: - invalid argument -- '$1'" 1>&2
		exit 1
    fi
    shift
done

if [ $PFLAG = 'true' ]; then
    getent passwd $USERID 2>/dev/null 1>&2
    USER_EXISTS=$(echo $?)
fi

if [[ ! $LENGTH =~ ^-?[0-9]+$ ]]; then
    echo "passgen: password length  -- '$LENGTH' not a number" 1>&2
    exit 1	    
elif [ $LENGTH -le 0 ]; then
    echo "passgen: invalid -n argument '$LENGTH' <= 0" 1>&2
    exit 1
elif [ $PFLAG = 'true' ] && [ $EUID -ne 0 ]; then
	echo "passgen: -p flag must be run with administrative privileges" 1>&2
	exit 1
elif [ $PFLAG = 'true' ] && [ $USER_EXISTS -ne 0 ]; then
    echo "passgen: '-p' argument -- '$USERID' not a valid user" 1>&2
    exit 1    
else
    if [ $LFLAG = 'false' -a $UFLAG = 'false' -a $DFLAG = 'false' -a $SFLAG = 'false' ]; then
		LFLAG=true
    fi
    
    if [ $EFLAG = 'true' ]; then
		LOWER="a-km-z"
		UPPER="A-HJ-NP-Z"
		DIGITS="2-9"
    fi
    
    CHARS=''
    if [ $LFLAG = 'true' ]; then
		CHARS="$LOWER$CHARS"
    fi
    if [ $UFLAG = 'true' ]; then
		CHARS="$UPPER$CHARS"
    fi
    if [ $DFLAG = 'true' ]; then
		CHARS="$DIGITS$CHARS"
    fi
    if [ $SFLAG = 'true' ]; then
		CHARS="$SYMBOL$CHARS"
    fi

	PW=`tr -dc $CHARS < /dev/urandom | head -c${1:-$LENGTH};echo;`
    if [ $PFLAG = 'true' ]; then
		sudo passwd $USERID 1>/dev/null 2>&1 <<EOF
$PW
$PW
EOF
	fi
	echo $PW
fi
